appname: "App::BlogAlba"
layout: "main"
charset: "UTF-8"
tz: "Europe/London"
locale: "en_GB"

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      encoding:  'utf8'
      start_tag: '[%'
      end_tag:   '%]'